# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master    # Declenche le pipeline a chaque modification sur la branche 'master'.

pool: 'default' # Definit le pool d'agents par defaut pour executer les taches.

variables:
 - name: CloudInitContent  # Variable pour stocker le contenu encode en Base64.
   value: ''

steps:  # Commence la liste des etapes a executer dans ce pipeline.
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students(1)(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'KeyRessourceGroup'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\KeyVaultRG\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\KeyVaultRG\azuredeploy.parameters.json'
    deploymentMode: 'Validation'
# Cette etape valide le modele ARM (fichier `azuredeploy.json`) avant de le deployer dans le groupe de ressources 'KeyRessourceGroup' dans la region 'East US'.
# Ce deploiement est defini sur "Validation", donc aucune ressource n'est creee ou modifiee ; cela sert uniquement a verifier la syntaxe et les dependances du modele.
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'vmsscire'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\VMSS\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\VMSS\azuredeploy.parameters.json'
    overrideParameters: '-adminPassword $(adminPass) -customData $(CloudInitContent)'
    deploymentMode: 'Validation'
# Cette etape valide un autre modele ARM pour le groupe de ressources 'vmsscire' dans la region 'Canada Central'.
# Les parametres `adminPassword` et `customData` sont remplaces par des valeurs specifiques pour ce deploiement.
# Le mode de deploiement est encore "Validation", donc cette etape verifie simplement le modele sans effectuer de modifications.