
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master        # Declenche le pipeline a chaque modification sur la branche 'master'.

pool: "default"  # Definit le pool d'agents par defaut pour executer les taches.

variables:
 -name: CloudInitContent  # Variable pour stocker le contenu encode en Base64.

steps:

# Validation du modele ARM avant deploiement
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Projet1'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\azuredeploy.parameters.json'
    deploymentMode: 'Validation'
# Recuperation d'un secret depuis Azure Key Vault
- task: AzureKeyVault@2
  name: AzureKey
  inputs:
    azureSubscription: 'Azure for Students(1)(0673c009-6d00-4254-9178-35fed48c87be)'
    KeyVaultName: 'VaultProjet1'
    SecretsFilter: 'codesecret'
    RunAsPreJob: false
- script: echo New Value $(AzureKey.codesecret)
  displayName: 'step 2.1'
# Encodage d'un fichier en Base64 pour utilisation dans ARM
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path "$(Build.SourcesDirectory)\Cloud-Init.txt" -Raw
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"
- script: |
    echo $(CloudInitContent)
# Deploiement incremental avec modele ARM et donnees personnalisees
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Projet1'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent)'
    deploymentMode: 'Incremental'
# Deploiement dans une autre region avec parametres similaires  
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Abonnement Azure PAYG(1)(0673c009-6d00-4254-9178-35fed48c87be)'
      subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'Projet1'
      location: 'East US'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\azuredeploy.parameters.json'
      overrideParameters: '-customData "$(CloudInitContent)"'
      deploymentMode: 'Incremental'
# Validation finale du modele dans une autre region
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students(1)(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Projet1'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\azuredeploy.parameters.json'
    deploymentMode: 'Validation'
# Derniere etape de deploiement incremental avec toutes les configurations
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Projet1'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\azuredeploy.parameters.json'
    overrideParameters: '-customData "$(CloudInitContent)"'
    deploymentMode: 'Incremental' # Mode de deploiement final pour ajouter ou mettre a jour les ressources.