
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master        # Declenche le pipeline a chaque modification sur la branche 'master'.

pool: "default"  # Definit le pool d'agents par defaut pour executer les taches.

variables:
 -name: CloudInitContent  # Variable pour stocker le contenu encode en Base64.

steps:

# Validation du modele ARM avant deploiement
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students(1)(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'KeyRessourceGroup'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\KeyVaultRG\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\KeyVaultRG\azuredeploy.parameters.json'
    deploymentMode: 'Incremental'

# Recuperation d'un secret depuis Azure Key Vault
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure for Students(0673c009-6d00-4254-9178-35fed48c87be)'
    KeyVaultName: 'tpkeysalifou'
    SecretsFilter: '*'
    SecretsAction: 'Create'
    SecretName: 'adminPass'
    SecretValue: $(adminPass)
    RunAsPreJob: false

# Encodage d'un fichier en Base64 pour utilisation dans ARM
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path "$(Build.SourcesDirectory)\Cloud-Init.txt" -Raw
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'vmsscire'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\VMSS\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\VMSS\azuredeploy.parameters.json'
    overrideParameters: '-adminPassword $(adminPass) -customData $(CloudInitContent)'
    deploymentMode: 'Incremental'